"use client"

import { useState, useEffect, useCallback } from "react"
import { createClient } from "@/lib/supabase/client"
import ScheduleHeader from "@/components/schedule-header"
import MonthCalendar from "@/components/month-calendar"
import EmployeeManagement from "@/components/employee-management"
import StatisticsPanel from "@/components/statistics-panel"
import ScheduleGenerator from "@/components/schedule-generator"
import VacationManagement from "@/components/vacation-management"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardContent } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Toaster } from "@/components/ui/toaster"
import { useToast } from "@/components/ui/use-toast"
import { ChevronLeft, ChevronRight, RotateCcw, Loader2 } from "lucide-react"
import { ScheduleSkeleton } from "@/components/schedule-skeleton"
import MonthSummary from "@/components/month-summary"

export default function SchedulePage() {
  const [currentDate, setCurrentDate] = useState<Date>(new Date(2026, 4, 1))
  const [employees, setEmployees] = useState<any[]>([])
  const [schedules, setSchedules] = useState<any>({})
  const [vacations, setVacations] = useState<any>({})
  const [autoGenerated, setAutoGenerated] = useState(false)
  const [mounted, setMounted] = useState(false)
  const [loading, setLoading] = useState(true)
  const [savingShift, setSavingShift] = useState(false)
  const [clearingMonth, setClearingMonth] = useState(false)
  const [generatingSchedule, setGeneratingSchedule] = useState(false)
  const [activeTab, setActiveTab] = useState("calendar")
  const [isSaving, setIsSaving] = useState(false)

  const { toast } = useToast()
  const supabase = createClient()

  const [dataCache, setDataCache] = useState<{
    employees: any[]
    schedules: any
    vacations: any
    timestamp: number
  } | null>(null)

  const CACHE_DURATION = 5 * 60 * 1000 // 5 minutos

  const handleClearMonth = useCallback(async () => {
    if (!(currentDate instanceof Date) || isNaN(currentDate.getTime())) {
      toast({
        title: "Error",
        description: "Fecha inválida",
        variant: "destructive",
      })
      return
    }

    setClearingMonth(true)
    try {
      const monthKey = `${currentDate.getFullYear()}-${currentDate.getMonth()}`
      setSchedules((prev: any) => {
        const updated = { ...prev }
        delete updated[monthKey]
        return updated
      })

      const { error } = await supabase.from("schedules").delete().eq("month_key", monthKey)

      if (error) {
        console.error("[v0] Error clearing month:", error)
        toast({
          variant: "destructive",
          title: "Error al limpiar mes",
          description: error.message || "No se pudo limpiar el mes",
        })
        throw error
      }

      toast({
        title: "Mes limpiado",
        description: `Todos los guardias para ${monthKey} han sido eliminados`,
      })
    } catch (error) {
      console.error("[v0] Error clearing month:", error)
    } finally {
      setClearingMonth(false)
    }
  }, [currentDate, supabase, toast])

  useEffect(() => {
    async function loadData() {
      try {
        console.log("[v0] Loading data from Supabase...")

        const [employeesResult, vacationsResult, schedulesResult] = await Promise.all([
          supabase.from("employees").select("*").order("rank", { ascending: false }),
          supabase.from("vacation_days").select("*"),
          supabase.from("schedules").select("*"),
        ])

        if (employeesResult.error) {
          console.error("[v0] Error loading employees:", employeesResult.error)
          toast({
            variant: "destructive",
            title: "Error al cargar empleados",
            description: employeesResult.error.message || "No se pudieron cargar los empleados de la base de datos",
          })
          throw employeesResult.error
        }

        if (vacationsResult.error) {
          console.error("[v0] Error loading vacations:", vacationsResult.error)
          toast({
            variant: "destructive",
            title: "Error al cargar vacaciones",
            description: vacationsResult.error.message || "No se pudieron cargar las vacaciones de la base de datos",
          })
          throw vacationsResult.error
        }

        if (schedulesResult.error) {
          console.error("[v0] Error loading schedules:", schedulesResult.error)
          toast({
            variant: "destructive",
            title: "Error al cargar planillas",
            description: schedulesResult.error.message || "No se pudieron cargar las planillas de la base de datos",
          })
          throw schedulesResult.error
        }

        const employeesData = employeesResult.data
        const vacationsData = vacationsResult.data
        const schedulesData = schedulesResult.data

        console.log(`[v0] Loaded ${employeesData?.length || 0} employees`)
        console.log(`[v0] Loaded ${vacationsData?.length || 0} vacation days`)
        console.log(`[v0] Loaded ${schedulesData?.length || 0} schedule entries`)

        const employeesWithVacations = employeesData.map((emp: any) => {
          const empVacations = vacationsData.filter((v: any) => v.employee_id === emp.id)
          const vacationDays: any = {}

          empVacations.forEach((v: any) => {
            if (!vacationDays[v.month_key]) {
              vacationDays[v.month_key] = []
            }
            vacationDays[v.month_key].push(v.day)
          })

          return {
            id: emp.id,
            name: emp.name,
            rank: emp.rank,
            vacationDays,
            preferences: {},
          }
        })

        setEmployees(employeesWithVacations)

        const schedulesObj: any = {}
        schedulesData.forEach((s: any) => {
          if (!schedulesObj[s.month_key]) {
            schedulesObj[s.month_key] = {}
          }
          schedulesObj[s.month_key][s.day] = s.employee_id
        })

        setSchedules(schedulesObj)

        const vacationsObj: any = {}
        vacationsData.forEach((v: any) => {
          if (!vacationsObj[v.month_key]) {
            vacationsObj[v.month_key] = {}
          }
          vacationsObj[v.month_key][v.day] = v.employee_id
        })

        setVacations(vacationsObj)

        setDataCache({
          employees: employeesWithVacations,
          schedules: schedulesObj,
          vacations: vacationsObj,
          timestamp: Date.now(),
        })

        toast({
          title: "Datos cargados correctamente",
          description: `${employeesData.length} empleados y ${schedulesData.length} guardias cargadas`,
        })
      } catch (error) {
        console.error("[v0] Error loading data from Supabase:", error)
        toast({
          variant: "destructive",
          title: "Error crítico",
          description: "No se pudieron cargar los datos. Por favor, recarga la página.",
        })
      } finally {
        setLoading(false)
        setMounted(true)
      }
    }

    if (dataCache && Date.now() - dataCache.timestamp < CACHE_DURATION) {
      console.log("[v0] Using cached data")
      setEmployees(dataCache.employees)
      setSchedules(dataCache.schedules)
      setVacations(dataCache.vacations)
      setLoading(false)
      setMounted(true)
    } else {
      loadData()
    }
  }, [])

  const currentMonth = currentDate.getMonth()
  const currentYear = currentDate.getFullYear()
  const monthKey = `${currentYear}-${currentMonth}`

  const handlePreviousMonth = () => {
    setCurrentDate(new Date(currentDate.getFullYear(), currentDate.getMonth() - 1, 1))
  }

  const handleNextMonth = () => {
    setCurrentDate(new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 1))
  }

  const assignShift = useCallback(
    async (day: number, employeeId: string) => {
      setSavingShift(true)
      try {
        const monthKey = `${currentYear}-${currentMonth}`

        setSchedules((prev: any) => ({
          ...prev,
          [monthKey]: {
            ...prev[monthKey],
            [day]: employeeId,
          },
        }))

        const { error } = await supabase.from("schedules").upsert(
          {
            month_key: monthKey,
            day,
            employee_id: employeeId,
          },
          { onConflict: "month_key,day" },
        )

        if (error) {
          // Revertir cambio local si falla
          setSchedules((prev: any) => {
            const updated = { ...prev }
            if (updated[monthKey]) {
              delete updated[monthKey][day]
            }
            return updated
          })
          throw error
        }

        toast({
          title: "Guardia asignada",
          description: `${employees.find((e) => e.id === employeeId)?.name} asignado al día ${day}`,
        })
      } catch (error: any) {
        console.error("[v0] Error assigning shift:", error)
        toast({
          variant: "destructive",
          title: "Error al asignar guardia",
          description: error.message || "No se pudo guardar la asignación en la base de datos",
        })
      } finally {
        setSavingShift(false)
      }
    },
    [currentMonth, currentYear, employees, supabase, toast],
  )

  const removeShift = useCallback(
    async (day: number) => {
      setSavingShift(true)
      try {
        const monthKey = `${currentYear}-${currentMonth}`

        // Actualizar estado local inmediatamente
        const previousEmployeeId = schedules[monthKey]?.[day]
        setSchedules((prev: any) => {
          const updated = { ...prev }
          if (updated[monthKey]) {
            const newMonth = { ...updated[monthKey] }
            delete newMonth[day]
            updated[monthKey] = newMonth
          }
          return updated
        })

        // Sincronizar con Supabase
        const { error } = await supabase.from("schedules").delete().match({
          month_key: monthKey,
          day,
        })

        if (error) {
          // Revertir si falla
          setSchedules((prev: any) => ({
            ...prev,
            [monthKey]: {
              ...prev[monthKey],
              [day]: previousEmployeeId,
            },
          }))
          throw error
        }

        toast({
          title: "Guardia removida",
          description: `Día ${day} ahora disponible`,
        })
      } catch (error: any) {
        console.error("[v0] Error removing shift:", error)
        toast({
          variant: "destructive",
          title: "Error al remover guardia",
          description: error.message || "No se pudo eliminar la guardia de la base de datos",
        })
      } finally {
        setSavingShift(false)
      }
    },
    [currentMonth, currentYear, schedules, supabase, toast],
  )

  const handleAutoGenerate = async (generatedSchedule: any) => {
    setGeneratingSchedule(true)
    try {
      console.log("[v0] Generating schedule for", monthKey)

      const { error: deleteError } = await supabase.from("schedules").delete().eq("month_key", monthKey)

      if (deleteError) {
        console.error("[v0] Error deleting existing schedules:", deleteError)
        toast({
          variant: "destructive",
          title: "Error al limpiar guardias",
          description: deleteError.message || "No se pudo limpiar el mes antes de generar",
        })
        throw deleteError
      }

      const schedulesToInsert = Object.entries(generatedSchedule).map(([day, employeeId]) => ({
        month_key: monthKey,
        day: Number.parseInt(day),
        employee_id: employeeId,
      }))

      const { error } = await supabase.from("schedules").insert(schedulesToInsert)

      if (error) {
        console.error("[v0] Error saving schedule:", error)
        toast({
          variant: "destructive",
          title: "Error al guardar planilla",
          description: error.message || "No se pudo guardar la planilla generada",
        })
        throw error
      }

      setSchedules({ ...schedules, [monthKey]: generatedSchedule })
      setAutoGenerated(true)

      toast({
        title: "Planilla generada",
        description: `${Object.keys(generatedSchedule).length} guardias asignadas correctamente`,
      })
    } catch (error) {
      console.error("[v0] Error saving schedule:", error)
    } finally {
      setGeneratingSchedule(false)
    }
  }

  const handleUpdateVacation = async (employeeId: string, day: number, isVacation: boolean) => {
    try {
      console.log(`[v0] Updating vacation: employee ${employeeId}, day ${day}, isVacation ${isVacation}`)

      if (isVacation) {
        const { error } = await supabase
          .from("vacation_days")
          .upsert({ employee_id: employeeId, month_key: monthKey, day }, { onConflict: "employee_id,month_key,day" })

        if (error) {
          console.error("[v0] Error adding vacation:", error)
          toast({
            variant: "destructive",
            title: "Error al agregar vacaciones",
            description: error.message || `No se pudo agregar vacaciones para el día ${day}`,
          })
          throw error
        }
      } else {
        const { error } = await supabase
          .from("vacation_days")
          .delete()
          .eq("employee_id", employeeId)
          .eq("month_key", monthKey)
          .eq("day", day)

        if (error) {
          console.error("[v0] Error removing vacation:", error)
          toast({
            variant: "destructive",
            title: "Error al eliminar vacaciones",
            description: error.message || `No se pudo eliminar vacaciones del día ${day}`,
          })
          throw error
        }
      }

      const updatedEmployees = employees.map((emp) => {
        if (emp.id === employeeId) {
          const vacationDays = emp.vacationDays[monthKey] || []
          if (isVacation) {
            return { ...emp, vacationDays: { ...emp.vacationDays, [monthKey]: [...new Set([...vacationDays, day])] } }
          } else {
            return {
              ...emp,
              vacationDays: { ...emp.vacationDays, [monthKey]: vacationDays.filter((d: number) => d !== day) },
            }
          }
        }
        return emp
      })
      setEmployees(updatedEmployees)

      const employee = employees.find((e) => e.id === employeeId)
      toast({
        title: isVacation ? "Vacaciones añadidas" : "Vacaciones eliminadas",
        description: `${employee?.name || employeeId} - Día ${day}`,
      })
    } catch (error) {
      console.error("[v0] Error updating vacation:", error)
    }
  }

  const handleClearAllVacations = async () => {
    try {
      setIsSaving(true)
      console.log(`[v0] Clearing all vacations for month ${monthKey}`)

      const { error } = await supabase.from("vacation_days").delete().eq("month_key", monthKey)

      if (error) {
        console.error("[v0] Error clearing vacations:", error)
        toast({
          variant: "destructive",
          title: "Error al limpiar vacaciones",
          description: error.message || "No se pudieron eliminar las vacaciones del mes",
        })
        throw error
      }

      // Update local state
      const updatedEmployees = employees.map((emp) => ({
        ...emp,
        vacationDays: {
          ...emp.vacationDays,
          [monthKey]: [],
        },
      }))
      setEmployees(updatedEmployees)

      toast({
        title: "Vacaciones eliminadas",
        description: `Todas las vacaciones de ${currentDate?.toLocaleDateString("es-ES", { month: "long", year: "numeric" })} han sido eliminadas`,
      })
    } catch (error) {
      console.error("[v0] Error clearing all vacations:", error)
    } finally {
      setIsSaving(false)
    }
  }

  const handleAddEmployee = async (name: string, rank: string) => {
    try {
      console.log(`[v0] Adding employee: ${name} (${rank})`)

      const newEmployeeId = `${name.toLowerCase().replace(/\s+/g, "")}${rank.toLowerCase()}`

      const { error } = await supabase.from("employees").insert({ id: newEmployeeId, name, rank })

      if (error) {
        console.error("[v0] Error adding employee:", error)
        toast({
          variant: "destructive",
          title: "Error al agregar empleado",
          description: error.message || `No se pudo agregar a ${name}`,
        })
        throw error
      }

      const newEmployee = {
        id: newEmployeeId,
        name,
        rank,
        vacationDays: {},
        preferences: {},
      }
      setEmployees([...employees, newEmployee])

      toast({
        title: "Empleado agregado",
        description: `${name} (${rank}) ha sido agregado correctamente`,
      })
    } catch (error) {
      console.error("[v0] Error adding employee:", error)
    }
  }

  const handleRemoveEmployee = async (employeeId: string) => {
    try {
      console.log(`[v0] Removing employee: ${employeeId}`)

      const employee = employees.find((e) => e.id === employeeId)
      const { error } = await supabase.from("employees").delete().eq("id", employeeId)

      if (error) {
        console.error("[v0] Error removing employee:", error)
        toast({
          variant: "destructive",
          title: "Error al eliminar empleado",
          description: error.message || `No se pudo eliminar al empleado`,
        })
        throw error
      }

      setEmployees(employees.filter((emp) => emp.id !== employeeId))

      toast({
        title: "Empleado eliminado",
        description: `${employee?.name || employeeId} ha sido eliminado`,
      })
    } catch (error) {
      console.error("[v0] Error removing employee:", error)
    }
  }

  const handleEditEmployee = async (employeeId: string, name: string, rank: string) => {
    try {
      console.log(`[v0] Editing employee: ${employeeId} to ${name} (${rank})`)

      const { error } = await supabase.from("employees").update({ name, rank }).eq("id", employeeId)

      if (error) {
        console.error("[v0] Error editing employee:", error)
        toast({
          variant: "destructive",
          title: "Error al editar empleado",
          description: error.message || `No se pudo editar al empleado`,
        })
        throw error
      }

      const updatedEmployees = employees.map((emp) => (emp.id === employeeId ? { ...emp, name, rank } : emp))
      setEmployees(updatedEmployees)

      toast({
        title: "Empleado actualizado",
        description: `${name} (${rank}) ha sido actualizado correctamente`,
      })
    } catch (error) {
      console.error("[v0] Error editing employee:", error)
    }
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-background">
        <div className="container mx-auto p-4 md:p-6">
          <ScheduleSkeleton />
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 dark:from-slate-900 dark:to-slate-800">
      <ScheduleHeader />

      <main className="container mx-auto px-4 py-8 max-w-full">
        <Card className="bg-white dark:bg-slate-800 shadow-lg">
          <div className="p-6">
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white">
                {currentDate.toLocaleDateString("es-ES", {
                  year: "numeric",
                  month: "long",
                })}
              </h2>
              <div className="flex gap-2">
                <Button
                  variant="outline"
                  onClick={handlePreviousMonth}
                  disabled={currentYear === 2026 && currentMonth === 4}
                >
                  <ChevronLeft className="w-4 h-4" />
                </Button>
                <Button
                  variant="outline"
                  onClick={handleClearMonth}
                  disabled={clearingMonth}
                  className="text-red-600 bg-transparent"
                >
                  {clearingMonth ? (
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  ) : (
                    <RotateCcw className="w-4 h-4 mr-2" />
                  )}
                  {clearingMonth ? "Limpiando..." : "Limpiar mes"}
                </Button>
                <Button
                  variant="outline"
                  onClick={handleNextMonth}
                  disabled={currentYear === 2027 && currentMonth === 4}
                >
                  <ChevronRight className="w-4 h-4" />
                </Button>
              </div>
            </div>

            <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
              <TabsList className="grid w-full grid-cols-5">
                <TabsTrigger value="calendar">Calendario</TabsTrigger>
                <TabsTrigger value="employees">Empleados</TabsTrigger>
                <TabsTrigger value="vacations">Vacaciones</TabsTrigger>
                <TabsTrigger value="statistics">Estadísticas</TabsTrigger>
                <TabsTrigger value="generator">Generar</TabsTrigger>
              </TabsList>

              <TabsContent value="calendar" className="mt-6">
                <div className="flex flex-col lg:flex-row gap-6">
                  <div className="flex-1">
                    <Card>
                      <CardHeader className="flex flex-row items-center justify-between">
                        <MonthSummary schedules={schedules} monthKey={monthKey} employees={employees} />
                      </CardHeader>
                      <CardContent>
                        <MonthCalendar
                          year={currentYear}
                          month={currentMonth}
                          schedules={schedules[monthKey] || {}}
                          employees={employees}
                          vacations={vacations}
                          onAssignShift={assignShift}
                          onRemoveShift={removeShift}
                        />
                      </CardContent>
                    </Card>
                  </div>
                </div>
              </TabsContent>

              <TabsContent value="employees" className="mt-6">
                <EmployeeManagement
                  employees={employees}
                  monthKey={monthKey}
                  currentDate={currentDate}
                  onUpdateVacation={handleUpdateVacation}
                  onAddEmployee={handleAddEmployee}
                  onRemoveEmployee={handleRemoveEmployee}
                  onEditEmployee={handleEditEmployee}
                />
              </TabsContent>

              <TabsContent value="vacations" className="mt-6">
                <VacationManagement
                  employees={employees}
                  monthKey={monthKey}
                  currentDate={currentDate}
                  onUpdateVacation={handleUpdateVacation}
                  onClearAllVacations={handleClearAllVacations}
                />
              </TabsContent>

              <TabsContent value="statistics" className="mt-6">
                <StatisticsPanel
                  employees={employees}
                  schedules={schedules}
                  monthKey={monthKey}
                  currentMonth={currentMonth}
                  currentYear={currentYear}
                />
              </TabsContent>

              <TabsContent value="generator" className="mt-6">
                <ScheduleGenerator
                  employees={employees}
                  schedules={schedules}
                  monthKey={monthKey}
                  currentMonth={currentMonth}
                  currentYear={currentYear}
                  onGenerate={handleAutoGenerate}
                  isGenerating={generatingSchedule}
                />
              </TabsContent>
            </Tabs>
          </div>
        </Card>
      </main>

      <Toaster />
    </div>
  )
}
